# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intercom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eintercom.proto\" \n\nPayRequest\x12\x12\n\ninvoice_in\x18\x01 \x01(\t\"\x1f\n\x0bPayResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32+\n\x07Invoice\x12 \n\x03Pay\x12\x0b.PayRequest\x1a\x0c.PayResponseb\x06proto3')



_PAYREQUEST = DESCRIPTOR.message_types_by_name['PayRequest']
_PAYRESPONSE = DESCRIPTOR.message_types_by_name['PayResponse']
PayRequest = _reflection.GeneratedProtocolMessageType('PayRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYREQUEST,
  '__module__' : 'intercom_pb2'
  # @@protoc_insertion_point(class_scope:PayRequest)
  })
_sym_db.RegisterMessage(PayRequest)

PayResponse = _reflection.GeneratedProtocolMessageType('PayResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYRESPONSE,
  '__module__' : 'intercom_pb2'
  # @@protoc_insertion_point(class_scope:PayResponse)
  })
_sym_db.RegisterMessage(PayResponse)

_INVOICE = DESCRIPTOR.services_by_name['Invoice']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYREQUEST._serialized_start=18
  _PAYREQUEST._serialized_end=50
  _PAYRESPONSE._serialized_start=52
  _PAYRESPONSE._serialized_end=83
  _INVOICE._serialized_start=85
  _INVOICE._serialized_end=128
# @@protoc_insertion_point(module_scope)
